### ISSUE TITLE
How to test dll c#

### ISSUE THREAD

**Issue by autoprog** [rnd-ash/Macchina-J2534#7]
hi,
compiling Firmware.ino = ok, test PCOMM ok (usb)
compiling driver = ok on vscode  macchina_pt_driver.dll =ok

how to test dll with c#  [ loader dll ]
or other way

thanks,
Carlos

**Comment by rnd-ash** [comment]
You need an application that can utilise the passthru (j2534) API.

**Comment by autoprog** [comment]
hi ash,

my test = sucess
connected CAN ok, send/receive frame = ok
see:
**Name: Macchina M2 UTD Passthru
Connected J2534 devices : STATUS_NOERROR
FirmwareVersion: 1.0.0_M2
DllVersion     : 0.5.0
ApiVersion     : 04.04
Status     : STATUS_NOERROR**

thanks,
Carlos.
